import json
import logging
from typing import Optional
import boto3
from botocore.exceptions import ClientError, NoCredentialsError
from app.core.config import settings

logger = logging.getLogger(__name__)


def get_bedrock_client():
    """Create and return a Bedrock runtime client."""
    try:
        # Get AWS credentials from settings
        credentials = settings.get_aws_credentials()
        
        client = boto3.client(
            "bedrock-runtime",
            region_name=settings.aws_region,
            **credentials
        )
        return client
    except Exception as e:
        logger.error(f"Failed to create Bedrock client: {e}")
        raise


def generate_ai_message(prompt: str) -> str:
    """
    Generate an AI message using Claude 3 Haiku via Amazon Bedrock.
    
    Args:
        prompt: The prompt to send to Claude
        
    Returns:
        Generated message from Claude
        
    Raises:
        Exception: If AI generation fails
    """
    try:
        # Check if AWS credentials are configured
        if not settings.is_aws_configured():
            raise Exception("AWS credentials not configured. Please set AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY in your .env file.")
        
        # Create Bedrock client
        client = get_bedrock_client()
        
        # Prepare the request body for Claude 3 Haiku
        body = {
            "anthropic_version": "bedrock-2023-05-31",
            "max_tokens": 1000,
            "messages": [
                {
                    "role": "user",
                    "content": prompt
                }
            ]
        }
        
        # Call Bedrock
        response = client.invoke_model(
            modelId=settings.bedrock_model_id,
            body=json.dumps(body),
            contentType="application/json",
            accept="application/json"
        )
        
        # Parse the response
        response_body = json.loads(response["body"].read())
        
        if "content" in response_body and len(response_body["content"]) > 0:
            generated_text = response_body["content"][0]["text"]
            logger.info("AI message generated successfully")
            return generated_text.strip()
        else:
            raise Exception("No content generated by Claude")
            
    except NoCredentialsError:
        logger.error("AWS credentials not found")
        raise Exception("AWS credentials not found. Please configure your AWS credentials.")
    except ClientError as e:
        error_code = e.response.get("Error", {}).get("Code", "Unknown")
        error_message = e.response.get("Error", {}).get("Message", "Unknown error")
        logger.error(f"AWS Bedrock error: {error_code} - {error_message}")
        raise Exception(f"AWS Bedrock error: {error_message}")
    except Exception as e:
        logger.error(f"AI generation failed: {e}")
        raise Exception(f"AI generation failed: {str(e)}")


def generate_lead_message(vacancy_title: str, company_name: str, user_company_name: str = None, user_company_website: str = None, additional_instructions: str = None) -> str:
    """
    Generate a professional outreach message for a lead.
    
    Args:
        vacancy_title: The job title from the vacancy
        company_name: The company name
        user_company_name: The user's company name for personalization
        user_company_website: The user's company website
        additional_instructions: Custom instructions for the AI (language, tone, recipient, etc.)
        
    Returns:
        Generated outreach message
    """
    # Build the base prompt
    if user_company_name:
        # Personalized message with user's company context
        company_context = f"from {user_company_name}"
        if user_company_website:
            company_context += f" ({user_company_website})"
        
        base_prompt = f"""Write a short, professional message offering staffing services to a company hiring a {vacancy_title} at {company_name}. 

You are writing {company_context}. The message should:
- Be concise (2-3 sentences)
- Mention your company name ({user_company_name}) to establish credibility
- Emphasize your company's expertise, quick candidate delivery, and technical knowledge
- Sound professional and confident
- Be suitable for a LinkedIn message or email
- Make it personal and credible"""
    else:
        # Generic message without company context
        base_prompt = f"""Write a short, professional message offering staffing services to a company hiring a {vacancy_title} at {company_name}. 

The message should:
- Be concise (2-3 sentences)
- Emphasize quick candidate delivery and technical expertise
- Sound professional and confident
- Be suitable for a LinkedIn message or email"""
    
    # Add additional instructions if provided
    if additional_instructions and additional_instructions.strip():
        base_prompt += f"\n\nAdditional instructions: {additional_instructions.strip()}"
    
    # Complete the prompt
    prompt = base_prompt + "\n\nFormat the response as a direct message without any additional formatting or explanations."
    
    return generate_ai_message(prompt)
